apiVersion: v1
kind: Secret
metadata:
  name: employee-db-credentials
  namespace: employee-services
type: Opaque
stringData:
  host: "postgres.employee-services.svc.cluster.local"
  database: "employees"
  username: "admin"
  password: "SecurePass123!"